// Code generated by goctl. DO NOT EDIT.
package types

type User struct {
	Id       int64  `json:"id"`
	Mobile   string `json:"mobile"`
	Nickname string `json:"nickname"`
	Sex      int64  `json:"sex"`
	Avatar   string `json:"avatar"`
	Info     string `json:"info"`
}

type UserInfoReq struct {
	Id int64 `json:"id"`
}

type UserInfoResp struct {
	UserInfo User `json:"userInfo"`
}
